### ISSUE TITLE
Error loading dll

### ISSUE THREAD

**Issue by mablebee** [alphaleonis/AlphaVSS#10]
Hi,

I tried to implement some code around your Classes and faced an issue at runtime (System.IO.FileNotFoundException). Then I tried the standalone AlphaShadow.exe and this is the output:

`AlphaShadow v1.3 - AlphaVSS Volume Shadow Copy Library Sample Client
Copyright © Peter Palotas 2008-2012

Error: Could not load file or assembly 'AlphaVSS.x64.dll' or one of
       its dependencies. The specified module could not be found.`

Any ideas? Target-Platform is Windows Server 2012 R1 with .NET Framework 4.5.2 installed.`

Thanks and cheers, Martin

**Comment by wingers999** [comment]
Make sure you have the relevant Visual C++ runtimes installed on machines you are trying to run it on - the AlphaVss dll needs those to run

[https://www.microsoft.com/en-GB/download/details.aspx?id=40784](url)
