### ISSUE TITLE
Could Not Load file or assembly 'AlphaVSS.x64.dll'

### ISSUE THREAD

**Issue by hnieef** [alphaleonis/AlphaVSS#11]
Hi i write application using c# and it working fine in my laptop. after that i deploy to production machine but it failed to load assembly AlphaVss.x64.dll which i already include in bin folder

could you rectify why this happen

Thank you

**Comment by wingers999** [comment]
Make sure you have the relevant Visual C++ runtimes installed on machines you are trying to run it on - the AlphaVss dll needs those to run

[https://www.microsoft.com/en-GB/download/details.aspx?id=40784](url)

**Comment by MariuszPL55** [comment]
Hey, I have the same problem here, your link wingers999 doesn't work anymore.. Please give us a needed libs to fix the problem.

**Comment by wingers999** [comment]
For some reason the website showing is correct but the link it points to is taking you to a github page instead

The libs you need are the Visual C++ 2013 Redistributables

Link = [https://www.microsoft.com/en-GB/download/details.aspx?id=40784](url)

**Comment by wingers999** [comment]
For some reason the website showing is correct but the link it points to is taking you to a github page instead

The libs you need are the Visual C++ 2013 Redistributables

Link = https://www.microsoft.com/en-GB/download/details.aspx?id=40784

**Comment by MariuszPL55** [comment]
Ah I see, thanks for fast reply!

**Comment by alphaleonis** [comment]
Fixed the original link as well. Not sure what had happened there.

**Comment by jol64** [comment]
I am experiencing "System.IO.FileNotFoundException: Could not load file or assembly 'AlphaVSS.x86.dll' or one .. " as well, but I am sure I installed the VC ++ 2013 Redistributable (x86) Runtime - 12.0.40660, and the AlphaVSS.x86.dll is in the same (program) directory as AlphaVSS.Common.dll. Is there another dependency?
This is on a Windows 10 32bit.
Any hint what to try, check, fix?
Btw. the links are broken again, Microsoft obviously likes to reshuffle stuff.
Thanks,
Joachim

**Comment by VMaxx** [comment]
Targeting 32-bit on a 64 bit machine does this also.  It is checking if you're OS is 64 bit and then trying to load the library for 64 bit even if you had targeted your application to 32.   VssUtils.cs - GetPlatformSpecificAssemblyShortname seems to be the issue.  
I think it may need to be modified to use something like this:
```
<AssemblyName Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">MyExe_Debug_x86</AssemblyName>
    <AssemblyName Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">MyExe_Release_x86</AssemblyName>
    <AssemblyName Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">MyExe_Debug_x64</AssemblyName>
    <AssemblyName Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">MyExe_Release_x64</AssemblyName>
```

**Comment by hepter** [comment]
Manual solution of the problem.

Open the *.csproj file with your own notepad

     <PropertyGroup Condition="............">
    .....other props...
    
    <Prefer32Bit>false</Prefer32Bit>
    
     </PropertyGroup>
