### ISSUE TITLE
How can AlphaVSS to support Windows 2003

### ISSUE THREAD

**Issue by leer168** [alphaleonis/AlphaVSS#15]
I see the commint(4ab84b03267e2f4cb9a6cb2cbf044ed09192f8a6:Removed support for pre-vista OS),but now I need it for Windows 2003.

What can I do?

Thank you very much!

**Comment by alphaleonis** [comment]
Use an older version of AlphaVSS is all that I can recommend.  Microsoft stopped supporting Windows 2003 about two years ago, and considering the complexity of supporting pre-vista with regards to VSS I have no intention of continuing that either unfortunately.

**Comment by leer168** [comment]
Thanks for reply.
