### ISSUE TITLE
64Bit detection

### ISSUE THREAD

**Issue by zivillian** [alphaleonis/AlphaVSS#16]
I've found this project today, and stumbled upon the following sentence in the documentation:

> Note that your application must be built using “Prefer 32-bit” unchecked if the Platform Target is set to Any CPU. Also note that your application must be built for 64-bit to work on a 64-bit system (or Any CPU with Prefer 32-bit off), and in 32-bit to work on a 32-bit system.

After a quick look at the source it seems to me, that the name of the loaded platform binary is built in [GetPlatformSpecificAssemblyShortName()](https://github.com/alphaleonis/AlphaVSS/blob/aabf028bd6c9e1a7f590d7439db1f1062858fdfd/src/AlphaVSS.Common/Classes/VssUtils.cs#L32) which checks `Environment.Is64BitOperatingSystem`.
I would suggest replacing this check with the following code:
```csharp 
if (IntPtr.Size == 8)
    result.Append("x64");
  else
    result.Append("x86"); 
```
The [documentation](https://msdn.microsoft.com/de-de/library/system.intptr.size(v=vs.110).aspx) clearly states, that this property can be used to detect the process bitness:
> The value of this property is 4 in a 32-bit process, and 8 in a 64-bit process.

**Comment by alphaleonis** [comment]
Yes, but I don't want the process bitness, I need the operating system bitness, so to speak. So I do need `Environment.Is64BitOperatingSystem`. If this would differ the process bitness, then VSS will not work, hence the comment that the process must be built for (or run in) the same bitness as the operating system.
