### ISSUE TITLE
Add support for .NET Core

### ISSUE THREAD

**Issue by OFark** [alphaleonis/AlphaVSS#18]
I'm building a service with web interface, hence .net Core. Cannot get it to work with AlphaVSS. Specifically it claims it can't find AlphaVSS.x64. Also my project moans about the nuget package targeting .net framework with may not be compatible with .net core 2

**Comment by alphaleonis** [comment]
I haven't looked into this issue in detail, but a few quick searches suggests that .NET Core does not support C++/CLI, which is what makes up most of AlphaVSS.  If this is the case then that would indeed make it a pretty difficult task to get it over to .NET Core.

But please correct me if I'm wrong here.

**Comment by mnaiman** [comment]
I think this would be helpful as .NET core is spreading.
I dont think it is technical problem - of course it would not be multiplatform as .NET core is, but it is not expected.
https://github.com/dotnet/corefx/issues/24444

**Comment by mnaiman** [comment]
One more idea. 
COM part could be done in pure C++ way (without .NET) and than Common project could reference this using pinvoke interop - https://docs.microsoft.com/en-us/dotnet/standard/native-interop

**Comment by langebo** [comment]
I hope bringing this up again is not too big of an annoyance to you, but todays release of .net core 3.1-preview2 brings support for C++/CLI.

Announced here: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1-preview-2/

Making your library available to the .net core community would be greatly appreciated. We have multiple projects, that would benefit big time. And I know of at least two more development teams, that I spoke to recently about vss. (You see, our need to support vss was kind of urgent ;)

I would gladly support you, but my C/C++ skills are far from production grade software. If you can think of any other kind of help (aside from code contribution) that would make that job easier for you, feel encouraged to let me know. I will gladly support people who contribute such niche but very important tools like yours.

**Comment by alphaleonis** [comment]
@langebo Thanks for highlighting this. I was not aware that C++/CLI support was introduced in .NET Core. I will certainly look in to adding support for .NET Core 3.1, though I can't mke any promises.

**Comment by alphaleonis** [comment]
Just to give an initial report. Things are looking good, and I got a build working with .NET Core 3.1 preview.  It will take a little while longer to get things in order, but it is coming anyway. :)

**Comment by alphaleonis** [comment]
Fixed in 0519b2cae101906b8154d809a5223b1254ac644e

**Comment by alphaleonis** [comment]
@langebo If you want to try it out and see how it works I uploaded a pre-release package to https://github.com/alphaleonis/AlphaVSS/packages/56723
Make sure to read the changelog on the develop branch though, since there are some breaking changes.

**Comment by alphaleonis** [comment]
Nevermind just yet... still some issues that I need to work out.

**Comment by alphaleonis** [comment]
@langebo Okay, so there we go, there is now an alpha version [available on NuGet](https://www.nuget.org/packages/AlphaVSS/2.0.0-alpha0044). 

There is also new documentation at http://alphavss.alphaleonis.com/articles/getting_started.html which should get you started with the breaking changes.

Please try it out and let me know if you find anything that isn't working as expected.

A final version will not be released until .NET Core 3.1 is released in final.

**Comment by langebo** [comment]
@alphaleonis Wow that was quick, thanks for your effort.

I will take a closer look once I return home later this week.
