### ISSUE TITLE
AlphaVss 1.2.4003

### ISSUE THREAD

**Issue by laspinaja** [alphaleonis/AlphaVSS#19]
I downloaded from Github and tried to use this with a small console application however I keep getting the error  "Volume Shadow Copy Service error: An unexpected error was encountered examining the XML document.  The document is missing the BACKUP_COMPONENTS element. "

It is a Vb.net project and my reference is to AlphaVSS.60.x86.dll.

I looked in both AlphaVSS.60.x86.xml and AlphaVSS.Common.xml and do not see this element.  I cannot use version 1.4 because installing the VC++ 2017 components will be a big headache and I don't see 1.3 in Github.  Any thoughts on what I am missing?

Thanks

**Comment by alphaleonis** [comment]
The .xml files you're referring to is the generated documentation for AlphaVSS and has nothing to do with the error you encountered.  Impossible to say what you're doing wrong without more information. Suggest you check the official VSS documentation. Probably you are passing in an invalid XML-document to one of the methods expecting one.
