### ISSUE TITLE
A procedure imported by 'AlphaVSS.x86.dll' could not be loaded.

### ISSUE THREAD

**Issue by asKannan1986** [alphaleonis/AlphaVSS#20]
Hi,
The error is : **A procedure imported by 'AlphaVSS.x86.dll' could not be loaded.**

We got the issue from XP machine with 32 bit. Please guide us what is missing. Please do  the needful ASAP.

**Comment by alphaleonis** [comment]
Unfortunately I cannot give any assistance with regards to windows XP. Microsoft stopped supporting the OS over four years ago. Perhaps someone else has any ideas?

**Comment by rexren78** [comment]
I use Windows 2008 32bit. The error happen, too.

**Comment by rexren78** [comment]
Can you write an example command for AlphaShadow.exe to check if this only happens in my application?
