### ISSUE TITLE
NEW LOGO

### ISSUE THREAD

**Issue by rijal10** [alphaleonis/AlphaVSS#22]
Hello alphaleonis.!
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by alphaleonis** [comment]
It is not an app, it's a library actually. Why do you want to create a logo specifically for this project?

**Comment by rijal10** [comment]
iam so sorry!

**Comment by alphaleonis** [comment]
No need to apologize. Just wondering why you're offering to create a logo for a small library like this.  In any case I don't think we need a logo for this library, so while I'm thankful for your offer, I think your talents are better spent on more popular projects.
