### ISSUE TITLE
Can't use AlphaVSS in x86 app

### ISSUE THREAD

**Issue by glacasa** [alphaleonis/AlphaVSS#26]
I work on a .NET 4.6.1 app, built for platform x86, and I can't use AlphaVSS because it tries to load the AlphaVSS.x64 assembly.

I tried on an empty Console project : 

```cs 
using Alphaleonis.Win32.Vss;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            VssUtils.LoadImplementation();
        }
    }
}
```

If the app targets platform `x86` or `Any CPU` with 'Prefer 32-bit' checked, I get this error at runtime : 
System.BadImageFormatException: 'Impossible de charger le fichier ou l'assembly 'AlphaVSS.x64, Version=1.4.0.0, Culture=neutral, PublicKeyToken=959d3993561034e3' ou une de ses dépendances. Tentative de chargement d’un programme de format incorrect.'

When built for Any CPU or x64, it's ok.

I saw that there are both `AlphaVSS.x64.dll` and `AlphaVSS.x86.dll` in the NuGet package, do we have something to do to use the x86 assembly ?

**Comment by alphaleonis** [comment]
From the documentation on the main page:
> Note that your application must be built using “Prefer 32-bit” unchecked if the Platform Target is set to Any CPU. Also note that your application must be built for 64-bit to work on a 64-bit system (or Any CPU with Prefer 32-bit off), and in 32-bit to work on a 32-bit system.
