### ISSUE TITLE
How can I backup the mdf and ldf files with vss?

### ISSUE THREAD

**Issue by rewerma** [alphaleonis/AlphaVSS#31]
Hi,
When I create the snapshot by AlphaVSS, it seems not using SqlServer writer to freeze IO. 
The mdf and ldf files timestamp is the old. It is not flush.

May I do something to freeze IO and flush data when create the snapshot ?

**Comment by alphaleonis** [comment]
I don't have personal experience working with SQL Server backups using VSS unfortunately. Hoping someone else can be of assistance.

**Comment by jzabroski** [comment]
@rewerma ⚠️  You don't want to, **_especially on a production system_**. ⚠️  Look up Brent Ozar's blog for the details. https://www.brentozar.com/archive/2018/01/perils-vss-snaps/
