### ISSUE TITLE
How to create VSS Differential backup copies using alphavss?

### ISSUE THREAD

**Issue by subodh2691** [alphaleonis/AlphaVSS#35]
Hello,

I wanted to create differential copies of my data using alpha vss. Is there any way to achieve that? I tried changing backupstate to Differential and PartialFile support as True, but that leads to failure in taking snapshot. Pleas help.

**Comment by alphaleonis** [comment]
Unfortunately I have no experience with this, so I can only refer to the offical Microsoft documentation for VSS, or hope that someone else reads this and is able to help you.

**Comment by jol64** [comment]
high level summary: VSS does not really tell you what changed, but only ensures that whatever you copy is in a consistent state.  If you need to identify changes, USN Journal is a better (though not always complete) mechanism.
