### ISSUE TITLE
Is possible to create a Shadow copy on other volume?

### ISSUE THREAD

**Issue by jmmalcala** [alphaleonis/AlphaVSS#38]
Hi team,

First of all, thank so much for this great project. 

I was wondering, if AlphaVSS could create a transportable VSS copy from C: to other volume such X: , and then import from it.

Best regards.

**Comment by alphaleonis** [comment]
I can't say that I've tried this myself, but is there any methods needed by the steps outlined in the document [Importing Transportable Shadow Copied Volumes](https://docs.microsoft.com/en-us/windows/win32/vss/importing-transportable-shadow-copied-volumes) that are not exposed by AlphaVSS?  if not, I don't see why it shouldn't be possible.
