### ISSUE TITLE
Administrator rights

### ISSUE THREAD

**Issue by francescoformenti** [alphaleonis/AlphaVSS#6]
Hi,
I am using the 1.2.4000.3 version of the library because I still need to use fw 4.0.
I only tryed to call the IVssImplementation.GetSnapshotCompatibility method, but it seems to require to be run as administrator to work.
Is it mandatory to run as administrator or is there a way to run without administrative rights?
I am administrator on my machine and I also tried to add my user in the Backup Operators group, but I still need to run as administrator the test program.
Thanks
Francesco

**Comment by kapsiR** [comment]
What kind of error do you get?
As described in the docs:  UnauthorizedAccessException
"Caller does not have sufficient backup privileges or is not an administrator."
http://alphavss.alphaleonis.com/doc/1.3.0/api/html/AB07560B.htm
