### ISSUE TITLE
Add NuGet package

### ISSUE THREAD

**Issue by kenkendk** [alphaleonis/AlphaVSS#8]
There is an unofficial package, but it is outdated:
https://www.nuget.org/packages/AlphaVSS

It would be great if there was one offered by the original creators.

**Comment by alphaleonis** [comment]
Better late than never I suppose. At least now I'm ready to release a NuGet package, but I need to get a hold of the owner of the already published NuGet package so that he can transfer ownership to me. So I've sent him a mail, and waiting for a reply. Hopefully he'll cooperate.

**Comment by wezeku** [comment]
Perhaps another name, e.g. "AlphaVSS Official", could be used if @dabide can't be reached?

**Comment by dabide** [comment]
Sorry, I didn't see this. I will transfer it ASAP.

**Comment by dabide** [comment]
I have now added you as an owner, @alphaleonis. Feel free to remove me. :-)

**Comment by alphaleonis** [comment]
@dabide Great! Thank you so much! :)

**Comment by alphaleonis** [comment]
Better late than never. 1.4.0 is out as a NuGet package.
